allow pk;system proxy to take a server ID
xSke/PluralKit pull request #305
Opened 2021-04-06 06:35 UTC by Qyriad

So people can disable proxying in a server without outing themselves :)

2021-04-06 07:23 UTC, spiralw requested changes
Hey, thanks for the PR, this is very useful!
I've left a couple comments in the code~

2021-04-06 07:23 UTC, spiralw commented on PluralKit.Bot/Commands/SystemEdit.cs
> +            string word = ctx.PeekArgument() ?? throw new PKSyntaxError("You must pass either \"on\" or \"off\".");
This "match guild" code should probably be in `ContextEntityArgumentsExt`, similarly to "MatchChannel"

2021-04-06 07:23 UTC, spiralw commented on PluralKit.Bot/Commands/SystemEdit.cs
> +                ctx.Cache.TryGetGuild(guildId, out guild);
you need to check if guild is null here

2021-04-06 07:23 UTC, spiralw commented on PluralKit.Bot/Commands/SystemEdit.cs
> +                await ctx.Reply($"Message proxying in this server ({guild.Name.EscapeMarkdown()}) is now **enabled** for your system.");
can this say "in the server" instead of "in this server" if the command was ran in a DM?

2021-04-06 07:23 UTC, spiralw commented on PluralKit.Bot/Commands/SystemEdit.cs
> +                if (ctx.Channel.GuildId == null)
```suggestion
                if (ctx.Guild == null)
```

2021-04-06 15:58 UTC, Qyriad commented
Alright, changed some things around for those requests. I think it should be good now?

2021-04-26 14:38 UTC, Qyriad commented
Rebased on main.

2021-04-26 14:44 UTC, spiralw reviewed
Oh, seems I didn't hit send earlier, whoops. Almost looks good, just a small thing

2021-05-04 17:18 UTC, Qyriad commented on PluralKit.Bot/CommandSystem/ContextEntityArgumentsExt.cs
> +                ctx.PopArgument();
Is that the correct behavior? Currently the user-observed functionality is the same, but ideologically, if the user passes a string that parses as a `ulong`, it's clearly meant to be interpreted as a server ID and not one of the other arguments (like `on|off`). If it doesn't pop the argument, that's signally that the argument is open to be interpreted as something else, no?

We're fine with changing it if you still want us to, but we wanted to point that out first.

2021-05-04 17:19 UTC, Qyriad commented on PluralKit.Bot/CommandSystem/ContextEntityArgumentsExt.cs
> +                return ctx.Guild;
> This "match guild" code should probably be in ContextEntityArgumentsExt, similarly to "MatchChannel"
Oh whoops, we interpreted this to mean that entire logic should go in `MatchGuild`. We'll fix that right away.

2021-05-05 18:55 UTC, spiralw commented on PluralKit.Bot/CommandSystem/ContextEntityArgumentsExt.cs
> +                ctx.PopArgument();
I see what you mean, yeah, generally ulongs don't mean anything other than a Discord snowflake. Still, I'd rather it be consistent with other match methods tbh

2021-05-06 16:19 UTC, Qyriad commented on PluralKit.Bot/CommandSystem/ContextEntityArgumentsExt.cs
> +                ctx.PopArgument();
Gotcha, fixed.

2021-05-06 16:37 UTC, spiralw approved these changes

2021-05-07 08:35 UTC, xSke commented
Looks good! thank you - sorry for the delay here.

2021-05-07 08:35 UTC, merged