Group List Rework + Group Name Privacy
xSke/PluralKit pull request #409
Opened 2022-01-06 01:45 UTC by rladenson

I *think* everything except API stuff is done, lmk if I missed anything

2022-01-09 15:34 UTC, spiralw requested changes

2022-01-09 15:34 UTC, spiralw commented on PluralKit.Bot/Commands/Lists/ContextListExt.cs
> +    public static GroupListOptions ParseGroupListOptions(this Context ctx, LookupContext lookupCtx)
hmm, I wonder if there's any way to do this without duplicating the entire member list code. is there anything that can be shared between MemberListOptions and GroupListOptions?

2022-01-09 15:34 UTC, spiralw commented on PluralKit.Bot/Services/EmbedService.cs
> +        if (target.NamePrivacy.Get(pctx, target.DisplayName, null) != null)
please just check directly against NamePrivacy instead of seeing if .Get returns null

2022-01-09 15:34 UTC, spiralw commented on PluralKit.Core/Database/Views/DatabaseViewsExt.cs
> +        return conn.QueryAsync<ListedGroup>(query.ToString(),
```suggestion
        return conn.QueryAsync<ListedGroup>(
            query.ToString(),
```

2022-01-09 15:34 UTC, spiralw commented on PluralKit.Core/Models/PKGroup.cs
> +        group.MetadataPrivacy.Get(ctx, (Instant?)group.Created);
does this need a cast?

2022-01-09 15:34 UTC, spiralw commented on docs/content/api/models.md
> +* Group privacy keys: `name_privacy`, `description_privacy`, `icon_privacy`, `list_privacy`, `visibility`
missing `metadata`

2022-01-09 15:34 UTC, spiralw commented on docs/content/command-list.md
> +- `pk;group <group> privacy <name|description|icon|visibility|all> <public|private>` - Changes a group's privacy settings.
also missing `metadata`

2022-01-09 15:34 UTC, spiralw commented on docs/content/tips-and-tricks.md
> +|-by-name|-bn|Sort by member/group name (default)|
maybe a good idea to just remove member instead of adding group, I think "sort by name" is clear enough

2022-01-09 16:24 UTC, rladenson commented on PluralKit.Bot/Commands/Groups.cs
> +                    "This group's name is now hidden from other systems, and will be replaced by the group's display name.",
That's copypasted from the member one lol. Should I add that to both?

2022-01-09 16:25 UTC, spiralw commented on PluralKit.Bot/Commands/Groups.cs
> +                    "This group's name is now hidden from other systems, and will be replaced by the group's display name.",
sure!

2022-01-14 22:52 UTC, rladenson commented
@spiralw

2022-01-14 22:54 UTC, spiralw commented
Thanks, will look over this and #412 tonight

2022-01-15 01:33 UTC, spiralw commented
Merged in fcbaedcc9d1f9036f93d87a056a67d5686273fee

2022-01-15 01:33 UTC, closed without merging